# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/convnet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import hyperparams_pb2 as protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/convnet.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14protos/convnet.proto\x12\x06protos\x1a\x18protos/hyperparams.proto\"\xbb\x01\n\x07\x43onvnet\x12#\n\x08\x63rnn_net\x18\x01 \x01(\x0b\x32\x0f.protos.CrnnNetH\x00\x12 \n\x06resnet\x18\x02 \x01(\x0b\x32\x0e.protos.ResNetH\x00\x12)\n\x0bstn_convnet\x18\x03 \x01(\x0b\x32\x12.protos.StnConvnetH\x00\x12-\n\rtgn_deconvnet\x18\x04 \x01(\x0b\x32\x14.protos.TgnDeconvnetH\x00\x42\x0f\n\rconvnet_oneof\"\xf1\x01\n\x07\x43rnnNet\x12\x38\n\x08net_type\x18\x01 \x01(\x0e\x32\x17.protos.CrnnNet.NetType:\rSINGLE_BRANCH\x12-\n\x10\x63onv_hyperparams\x18\x02 \x01(\x0b\x32\x13.protos.Hyperparams\x12$\n\x15summarize_activations\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04tiny\x18\x04 \x01(\x08:\x05\x66\x61lse\"B\n\x07NetType\x12\x11\n\rSINGLE_BRANCH\x10\x00\x12\x10\n\x0cTWO_BRANCHES\x10\x01\x12\x12\n\x0eTHREE_BRANCHES\x10\x02\"\xcb\x02\n\x06ResNet\x12\x37\n\x08net_type\x18\x01 \x01(\x0e\x32\x16.protos.ResNet.NetType:\rSINGLE_BRANCH\x12\x35\n\tnet_depth\x18\x02 \x01(\x0e\x32\x17.protos.ResNet.NetDepth:\tRESNET_50\x12-\n\x10\x63onv_hyperparams\x18\x03 \x01(\x0b\x32\x13.protos.Hyperparams\x12$\n\x15summarize_activations\x18\x04 \x01(\x08:\x05\x66\x61lse\"B\n\x07NetType\x12\x11\n\rSINGLE_BRANCH\x10\x00\x12\x10\n\x0cTWO_BRANCHES\x10\x01\x12\x12\n\x0eTHREE_BRANCHES\x10\x02\"8\n\x08NetDepth\x12\r\n\tRESNET_30\x10\x00\x12\r\n\tRESNET_50\x10\x01\x12\x0e\n\nRESNET_100\x10\x02\"v\n\nStnConvnet\x12-\n\x10\x63onv_hyperparams\x18\x01 \x01(\x0b\x32\x13.protos.Hyperparams\x12$\n\x15summarize_activations\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04tiny\x18\x03 \x01(\x08:\x05\x66\x61lse\"c\n\x0cTgnDeconvnet\x12-\n\x10\x63onv_hyperparams\x18\x01 \x01(\x0b\x32\x13.protos.Hyperparams\x12$\n\x15summarize_activations\x18\x02 \x01(\x08:\x05\x66\x61lse'
  ,
  dependencies=[protos_dot_hyperparams__pb2.DESCRIPTOR,])



_CRNNNET_NETTYPE = _descriptor.EnumDescriptor(
  name='NetType',
  full_name='protos.CrnnNet.NetType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINGLE_BRANCH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TWO_BRANCHES', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THREE_BRANCHES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=424,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_CRNNNET_NETTYPE)

_RESNET_NETTYPE = _descriptor.EnumDescriptor(
  name='NetType',
  full_name='protos.ResNet.NetType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINGLE_BRANCH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TWO_BRANCHES', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THREE_BRANCHES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=424,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_RESNET_NETTYPE)

_RESNET_NETDEPTH = _descriptor.EnumDescriptor(
  name='NetDepth',
  full_name='protos.ResNet.NetDepth',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESNET_30', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESNET_50', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESNET_100', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=768,
  serialized_end=824,
)
_sym_db.RegisterEnumDescriptor(_RESNET_NETDEPTH)


_CONVNET = _descriptor.Descriptor(
  name='Convnet',
  full_name='protos.Convnet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crnn_net', full_name='protos.Convnet.crnn_net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resnet', full_name='protos.Convnet.resnet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stn_convnet', full_name='protos.Convnet.stn_convnet', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tgn_deconvnet', full_name='protos.Convnet.tgn_deconvnet', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='convnet_oneof', full_name='protos.Convnet.convnet_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=246,
)


_CRNNNET = _descriptor.Descriptor(
  name='CrnnNet',
  full_name='protos.CrnnNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_type', full_name='protos.CrnnNet.net_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='protos.CrnnNet.conv_hyperparams', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.CrnnNet.summarize_activations', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiny', full_name='protos.CrnnNet.tiny', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CRNNNET_NETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=490,
)


_RESNET = _descriptor.Descriptor(
  name='ResNet',
  full_name='protos.ResNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='net_type', full_name='protos.ResNet.net_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='net_depth', full_name='protos.ResNet.net_depth', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='protos.ResNet.conv_hyperparams', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.ResNet.summarize_activations', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESNET_NETTYPE,
    _RESNET_NETDEPTH,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=824,
)


_STNCONVNET = _descriptor.Descriptor(
  name='StnConvnet',
  full_name='protos.StnConvnet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='protos.StnConvnet.conv_hyperparams', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.StnConvnet.summarize_activations', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tiny', full_name='protos.StnConvnet.tiny', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=826,
  serialized_end=944,
)


_TGNDECONVNET = _descriptor.Descriptor(
  name='TgnDeconvnet',
  full_name='protos.TgnDeconvnet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv_hyperparams', full_name='protos.TgnDeconvnet.conv_hyperparams', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.TgnDeconvnet.summarize_activations', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=946,
  serialized_end=1045,
)

_CONVNET.fields_by_name['crnn_net'].message_type = _CRNNNET
_CONVNET.fields_by_name['resnet'].message_type = _RESNET
_CONVNET.fields_by_name['stn_convnet'].message_type = _STNCONVNET
_CONVNET.fields_by_name['tgn_deconvnet'].message_type = _TGNDECONVNET
_CONVNET.oneofs_by_name['convnet_oneof'].fields.append(
  _CONVNET.fields_by_name['crnn_net'])
_CONVNET.fields_by_name['crnn_net'].containing_oneof = _CONVNET.oneofs_by_name['convnet_oneof']
_CONVNET.oneofs_by_name['convnet_oneof'].fields.append(
  _CONVNET.fields_by_name['resnet'])
_CONVNET.fields_by_name['resnet'].containing_oneof = _CONVNET.oneofs_by_name['convnet_oneof']
_CONVNET.oneofs_by_name['convnet_oneof'].fields.append(
  _CONVNET.fields_by_name['stn_convnet'])
_CONVNET.fields_by_name['stn_convnet'].containing_oneof = _CONVNET.oneofs_by_name['convnet_oneof']
_CONVNET.oneofs_by_name['convnet_oneof'].fields.append(
  _CONVNET.fields_by_name['tgn_deconvnet'])
_CONVNET.fields_by_name['tgn_deconvnet'].containing_oneof = _CONVNET.oneofs_by_name['convnet_oneof']
_CRNNNET.fields_by_name['net_type'].enum_type = _CRNNNET_NETTYPE
_CRNNNET.fields_by_name['conv_hyperparams'].message_type = protos_dot_hyperparams__pb2._HYPERPARAMS
_CRNNNET_NETTYPE.containing_type = _CRNNNET
_RESNET.fields_by_name['net_type'].enum_type = _RESNET_NETTYPE
_RESNET.fields_by_name['net_depth'].enum_type = _RESNET_NETDEPTH
_RESNET.fields_by_name['conv_hyperparams'].message_type = protos_dot_hyperparams__pb2._HYPERPARAMS
_RESNET_NETTYPE.containing_type = _RESNET
_RESNET_NETDEPTH.containing_type = _RESNET
_STNCONVNET.fields_by_name['conv_hyperparams'].message_type = protos_dot_hyperparams__pb2._HYPERPARAMS
_TGNDECONVNET.fields_by_name['conv_hyperparams'].message_type = protos_dot_hyperparams__pb2._HYPERPARAMS
DESCRIPTOR.message_types_by_name['Convnet'] = _CONVNET
DESCRIPTOR.message_types_by_name['CrnnNet'] = _CRNNNET
DESCRIPTOR.message_types_by_name['ResNet'] = _RESNET
DESCRIPTOR.message_types_by_name['StnConvnet'] = _STNCONVNET
DESCRIPTOR.message_types_by_name['TgnDeconvnet'] = _TGNDECONVNET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Convnet = _reflection.GeneratedProtocolMessageType('Convnet', (_message.Message,), {
  'DESCRIPTOR' : _CONVNET,
  '__module__' : 'protos.convnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.Convnet)
  })
_sym_db.RegisterMessage(Convnet)

CrnnNet = _reflection.GeneratedProtocolMessageType('CrnnNet', (_message.Message,), {
  'DESCRIPTOR' : _CRNNNET,
  '__module__' : 'protos.convnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.CrnnNet)
  })
_sym_db.RegisterMessage(CrnnNet)

ResNet = _reflection.GeneratedProtocolMessageType('ResNet', (_message.Message,), {
  'DESCRIPTOR' : _RESNET,
  '__module__' : 'protos.convnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.ResNet)
  })
_sym_db.RegisterMessage(ResNet)

StnConvnet = _reflection.GeneratedProtocolMessageType('StnConvnet', (_message.Message,), {
  'DESCRIPTOR' : _STNCONVNET,
  '__module__' : 'protos.convnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.StnConvnet)
  })
_sym_db.RegisterMessage(StnConvnet)

TgnDeconvnet = _reflection.GeneratedProtocolMessageType('TgnDeconvnet', (_message.Message,), {
  'DESCRIPTOR' : _TGNDECONVNET,
  '__module__' : 'protos.convnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.TgnDeconvnet)
  })
_sym_db.RegisterMessage(TgnDeconvnet)


# @@protoc_insertion_point(module_scope)
