# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/feature_extractor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import convnet_pb2 as protos_dot_convnet__pb2
from protos import bidirectional_rnn_pb2 as protos_dot_bidirectional__rnn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/feature_extractor.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eprotos/feature_extractor.proto\x12\x06protos\x1a\x14protos/convnet.proto\x1a\x1eprotos/bidirectional_rnn.proto\"\x8f\x01\n\x10\x46\x65\x61tureExtractor\x12 \n\x07\x63onvnet\x18\x01 \x01(\x0b\x32\x0f.protos.Convnet\x12\x33\n\x11\x62idirectional_rnn\x18\x02 \x03(\x0b\x32\x18.protos.BidirectionalRnn\x12$\n\x15summarize_activations\x18\x03 \x01(\x08:\x05\x66\x61lse'
  ,
  dependencies=[protos_dot_convnet__pb2.DESCRIPTOR,protos_dot_bidirectional__rnn__pb2.DESCRIPTOR,])




_FEATUREEXTRACTOR = _descriptor.Descriptor(
  name='FeatureExtractor',
  full_name='protos.FeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='convnet', full_name='protos.FeatureExtractor.convnet', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bidirectional_rnn', full_name='protos.FeatureExtractor.bidirectional_rnn', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.FeatureExtractor.summarize_activations', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=240,
)

_FEATUREEXTRACTOR.fields_by_name['convnet'].message_type = protos_dot_convnet__pb2._CONVNET
_FEATUREEXTRACTOR.fields_by_name['bidirectional_rnn'].message_type = protos_dot_bidirectional__rnn__pb2._BIDIRECTIONALRNN
DESCRIPTOR.message_types_by_name['FeatureExtractor'] = _FEATUREEXTRACTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureExtractor = _reflection.GeneratedProtocolMessageType('FeatureExtractor', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREEXTRACTOR,
  '__module__' : 'protos.feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:protos.FeatureExtractor)
  })
_sym_db.RegisterMessage(FeatureExtractor)


# @@protoc_insertion_point(module_scope)
