# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/loss.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/loss.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/loss.proto\x12\x06protos\"\xcd\x01\n\x04Loss\x12G\n\x1bsequence_cross_entropy_loss\x18\x01 \x01(\x0b\x32 .protos.SequenceCrossEntropyLossH\x00\x12\x36\n\x12l2_regression_loss\x18\x02 \x01(\x0b\x32\x18.protos.L2RegressionLossH\x00\x12\x36\n\x12l1_regression_loss\x18\x03 \x01(\x0b\x32\x18.protos.L1RegressionLossH\x00\x42\x0c\n\nloss_oneof\"p\n\x18SequenceCrossEntropyLoss\x12!\n\x12sequence_normalize\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x1e\n\x10sample_normalize\x18\x02 \x01(\x08:\x04true\x12\x11\n\x06weight\x18\x03 \x01(\x02:\x01\x31\"%\n\x10L2RegressionLoss\x12\x11\n\x06weight\x18\x03 \x01(\x02:\x01\x31\"%\n\x10L1RegressionLoss\x12\x11\n\x06weight\x18\x03 \x01(\x02:\x01\x31'
)




_LOSS = _descriptor.Descriptor(
  name='Loss',
  full_name='protos.Loss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_cross_entropy_loss', full_name='protos.Loss.sequence_cross_entropy_loss', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l2_regression_loss', full_name='protos.Loss.l2_regression_loss', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='l1_regression_loss', full_name='protos.Loss.l1_regression_loss', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='loss_oneof', full_name='protos.Loss.loss_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=235,
)


_SEQUENCECROSSENTROPYLOSS = _descriptor.Descriptor(
  name='SequenceCrossEntropyLoss',
  full_name='protos.SequenceCrossEntropyLoss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_normalize', full_name='protos.SequenceCrossEntropyLoss.sequence_normalize', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_normalize', full_name='protos.SequenceCrossEntropyLoss.sample_normalize', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='protos.SequenceCrossEntropyLoss.weight', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=349,
)


_L2REGRESSIONLOSS = _descriptor.Descriptor(
  name='L2RegressionLoss',
  full_name='protos.L2RegressionLoss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='protos.L2RegressionLoss.weight', index=0,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=388,
)


_L1REGRESSIONLOSS = _descriptor.Descriptor(
  name='L1RegressionLoss',
  full_name='protos.L1RegressionLoss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='protos.L1RegressionLoss.weight', index=0,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=427,
)

_LOSS.fields_by_name['sequence_cross_entropy_loss'].message_type = _SEQUENCECROSSENTROPYLOSS
_LOSS.fields_by_name['l2_regression_loss'].message_type = _L2REGRESSIONLOSS
_LOSS.fields_by_name['l1_regression_loss'].message_type = _L1REGRESSIONLOSS
_LOSS.oneofs_by_name['loss_oneof'].fields.append(
  _LOSS.fields_by_name['sequence_cross_entropy_loss'])
_LOSS.fields_by_name['sequence_cross_entropy_loss'].containing_oneof = _LOSS.oneofs_by_name['loss_oneof']
_LOSS.oneofs_by_name['loss_oneof'].fields.append(
  _LOSS.fields_by_name['l2_regression_loss'])
_LOSS.fields_by_name['l2_regression_loss'].containing_oneof = _LOSS.oneofs_by_name['loss_oneof']
_LOSS.oneofs_by_name['loss_oneof'].fields.append(
  _LOSS.fields_by_name['l1_regression_loss'])
_LOSS.fields_by_name['l1_regression_loss'].containing_oneof = _LOSS.oneofs_by_name['loss_oneof']
DESCRIPTOR.message_types_by_name['Loss'] = _LOSS
DESCRIPTOR.message_types_by_name['SequenceCrossEntropyLoss'] = _SEQUENCECROSSENTROPYLOSS
DESCRIPTOR.message_types_by_name['L2RegressionLoss'] = _L2REGRESSIONLOSS
DESCRIPTOR.message_types_by_name['L1RegressionLoss'] = _L1REGRESSIONLOSS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Loss = _reflection.GeneratedProtocolMessageType('Loss', (_message.Message,), {
  'DESCRIPTOR' : _LOSS,
  '__module__' : 'protos.loss_pb2'
  # @@protoc_insertion_point(class_scope:protos.Loss)
  })
_sym_db.RegisterMessage(Loss)

SequenceCrossEntropyLoss = _reflection.GeneratedProtocolMessageType('SequenceCrossEntropyLoss', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCECROSSENTROPYLOSS,
  '__module__' : 'protos.loss_pb2'
  # @@protoc_insertion_point(class_scope:protos.SequenceCrossEntropyLoss)
  })
_sym_db.RegisterMessage(SequenceCrossEntropyLoss)

L2RegressionLoss = _reflection.GeneratedProtocolMessageType('L2RegressionLoss', (_message.Message,), {
  'DESCRIPTOR' : _L2REGRESSIONLOSS,
  '__module__' : 'protos.loss_pb2'
  # @@protoc_insertion_point(class_scope:protos.L2RegressionLoss)
  })
_sym_db.RegisterMessage(L2RegressionLoss)

L1RegressionLoss = _reflection.GeneratedProtocolMessageType('L1RegressionLoss', (_message.Message,), {
  'DESCRIPTOR' : _L1REGRESSIONLOSS,
  '__module__' : 'protos.loss_pb2'
  # @@protoc_insertion_point(class_scope:protos.L1RegressionLoss)
  })
_sym_db.RegisterMessage(L1RegressionLoss)


# @@protoc_insertion_point(module_scope)
