# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import feature_extractor_pb2 as protos_dot_feature__extractor__pb2
from protos import predictor_pb2 as protos_dot_predictor__pb2
from protos import spatial_transformer_pb2 as protos_dot_spatial__transformer__pb2
from protos import text_generator_pb2 as protos_dot_text__generator__pb2
from protos import loss_pb2 as protos_dot_loss__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/model.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12protos/model.proto\x12\x06protos\x1a\x1eprotos/feature_extractor.proto\x1a\x16protos/predictor.proto\x1a protos/spatial_transformer.proto\x1a\x1bprotos/text_generator.proto\x1a\x11protos/loss.proto\"m\n\x05Model\x12U\n\"multi_predictors_recognition_model\x18\x01 \x01(\x0b\x32\'.protos.MultiPredictorsRecognitionModelH\x00\x42\r\n\x0bmodel_oneof\"\xb0\x02\n\x1fMultiPredictorsRecognitionModel\x12\x37\n\x13spatial_transformer\x18\x01 \x01(\x0b\x32\x1a.protos.SpatialTransformer\x12\x33\n\x11\x66\x65\x61ture_extractor\x18\x02 \x01(\x0b\x32\x18.protos.FeatureExtractor\x12$\n\tpredictor\x18\x03 \x03(\x0b\x32\x11.protos.Predictor\x12#\n\x14keypoint_supervision\x18\x04 \x01(\x08:\x05\x66\x61lse\x12%\n\x0fregression_loss\x18\x05 \x01(\x0b\x32\x0c.protos.Loss\x12-\n\x0etext_generator\x18\x06 \x01(\x0b\x32\x15.protos.TextGenerator'
  ,
  dependencies=[protos_dot_feature__extractor__pb2.DESCRIPTOR,protos_dot_predictor__pb2.DESCRIPTOR,protos_dot_spatial__transformer__pb2.DESCRIPTOR,protos_dot_text__generator__pb2.DESCRIPTOR,protos_dot_loss__pb2.DESCRIPTOR,])




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='protos.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_predictors_recognition_model', full_name='protos.Model.multi_predictors_recognition_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model_oneof', full_name='protos.Model.model_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=168,
  serialized_end=277,
)


_MULTIPREDICTORSRECOGNITIONMODEL = _descriptor.Descriptor(
  name='MultiPredictorsRecognitionModel',
  full_name='protos.MultiPredictorsRecognitionModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='spatial_transformer', full_name='protos.MultiPredictorsRecognitionModel.spatial_transformer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='protos.MultiPredictorsRecognitionModel.feature_extractor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictor', full_name='protos.MultiPredictorsRecognitionModel.predictor', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keypoint_supervision', full_name='protos.MultiPredictorsRecognitionModel.keypoint_supervision', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regression_loss', full_name='protos.MultiPredictorsRecognitionModel.regression_loss', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_generator', full_name='protos.MultiPredictorsRecognitionModel.text_generator', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=584,
)

_MODEL.fields_by_name['multi_predictors_recognition_model'].message_type = _MULTIPREDICTORSRECOGNITIONMODEL
_MODEL.oneofs_by_name['model_oneof'].fields.append(
  _MODEL.fields_by_name['multi_predictors_recognition_model'])
_MODEL.fields_by_name['multi_predictors_recognition_model'].containing_oneof = _MODEL.oneofs_by_name['model_oneof']
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['spatial_transformer'].message_type = protos_dot_spatial__transformer__pb2._SPATIALTRANSFORMER
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['feature_extractor'].message_type = protos_dot_feature__extractor__pb2._FEATUREEXTRACTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['predictor'].message_type = protos_dot_predictor__pb2._PREDICTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['regression_loss'].message_type = protos_dot_loss__pb2._LOSS
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['text_generator'].message_type = protos_dot_text__generator__pb2._TEXTGENERATOR
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['MultiPredictorsRecognitionModel'] = _MULTIPREDICTORSRECOGNITIONMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'protos.model_pb2'
  # @@protoc_insertion_point(class_scope:protos.Model)
  })
_sym_db.RegisterMessage(Model)

MultiPredictorsRecognitionModel = _reflection.GeneratedProtocolMessageType('MultiPredictorsRecognitionModel', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPREDICTORSRECOGNITIONMODEL,
  '__module__' : 'protos.model_pb2'
  # @@protoc_insertion_point(class_scope:protos.MultiPredictorsRecognitionModel)
  })
_sym_db.RegisterMessage(MultiPredictorsRecognitionModel)


# @@protoc_insertion_point(module_scope)
