# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rnn_cell.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import hyperparams_pb2 as protos_dot_hyperparams__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/rnn_cell.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15protos/rnn_cell.proto\x12\x06protos\x1a\x18protos/hyperparams.proto\"g\n\x07RnnCell\x12%\n\tlstm_cell\x18\x01 \x01(\x0b\x32\x10.protos.LstmCellH\x00\x12#\n\x08gru_cell\x18\x02 \x01(\x0b\x32\x0f.protos.GruCellH\x00\x42\x10\n\x0ernn_cell_oneof\"\x82\x01\n\x08LstmCell\x12\x16\n\tnum_units\x18\x01 \x01(\r:\x03\x31\x32\x38\x12\x1c\n\ruse_peepholes\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x16\n\x0b\x66orget_bias\x18\x03 \x01(\x02:\x01\x31\x12(\n\x0binitializer\x18\x04 \x01(\x0b\x32\x13.protos.Initializer\"K\n\x07GruCell\x12\x16\n\tnum_units\x18\x01 \x01(\r:\x03\x31\x32\x38\x12(\n\x0binitializer\x18\x02 \x01(\x0b\x32\x13.protos.Initializer'
  ,
  dependencies=[protos_dot_hyperparams__pb2.DESCRIPTOR,])




_RNNCELL = _descriptor.Descriptor(
  name='RnnCell',
  full_name='protos.RnnCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lstm_cell', full_name='protos.RnnCell.lstm_cell', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gru_cell', full_name='protos.RnnCell.gru_cell', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='rnn_cell_oneof', full_name='protos.RnnCell.rnn_cell_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=162,
)


_LSTMCELL = _descriptor.Descriptor(
  name='LstmCell',
  full_name='protos.LstmCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_units', full_name='protos.LstmCell.num_units', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_peepholes', full_name='protos.LstmCell.use_peepholes', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forget_bias', full_name='protos.LstmCell.forget_bias', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='protos.LstmCell.initializer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=295,
)


_GRUCELL = _descriptor.Descriptor(
  name='GruCell',
  full_name='protos.GruCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_units', full_name='protos.GruCell.num_units', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='protos.GruCell.initializer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=372,
)

_RNNCELL.fields_by_name['lstm_cell'].message_type = _LSTMCELL
_RNNCELL.fields_by_name['gru_cell'].message_type = _GRUCELL
_RNNCELL.oneofs_by_name['rnn_cell_oneof'].fields.append(
  _RNNCELL.fields_by_name['lstm_cell'])
_RNNCELL.fields_by_name['lstm_cell'].containing_oneof = _RNNCELL.oneofs_by_name['rnn_cell_oneof']
_RNNCELL.oneofs_by_name['rnn_cell_oneof'].fields.append(
  _RNNCELL.fields_by_name['gru_cell'])
_RNNCELL.fields_by_name['gru_cell'].containing_oneof = _RNNCELL.oneofs_by_name['rnn_cell_oneof']
_LSTMCELL.fields_by_name['initializer'].message_type = protos_dot_hyperparams__pb2._INITIALIZER
_GRUCELL.fields_by_name['initializer'].message_type = protos_dot_hyperparams__pb2._INITIALIZER
DESCRIPTOR.message_types_by_name['RnnCell'] = _RNNCELL
DESCRIPTOR.message_types_by_name['LstmCell'] = _LSTMCELL
DESCRIPTOR.message_types_by_name['GruCell'] = _GRUCELL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RnnCell = _reflection.GeneratedProtocolMessageType('RnnCell', (_message.Message,), {
  'DESCRIPTOR' : _RNNCELL,
  '__module__' : 'protos.rnn_cell_pb2'
  # @@protoc_insertion_point(class_scope:protos.RnnCell)
  })
_sym_db.RegisterMessage(RnnCell)

LstmCell = _reflection.GeneratedProtocolMessageType('LstmCell', (_message.Message,), {
  'DESCRIPTOR' : _LSTMCELL,
  '__module__' : 'protos.rnn_cell_pb2'
  # @@protoc_insertion_point(class_scope:protos.LstmCell)
  })
_sym_db.RegisterMessage(LstmCell)

GruCell = _reflection.GeneratedProtocolMessageType('GruCell', (_message.Message,), {
  'DESCRIPTOR' : _GRUCELL,
  '__module__' : 'protos.rnn_cell_pb2'
  # @@protoc_insertion_point(class_scope:protos.GruCell)
  })
_sym_db.RegisterMessage(GruCell)


# @@protoc_insertion_point(module_scope)
