# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/text_generator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import convnet_pb2 as protos_dot_convnet__pb2
from protos import hyperparams_pb2 as protos_dot_hyperparams__pb2
from protos import loss_pb2 as protos_dot_loss__pb2
from protos import bidirectional_rnn_pb2 as protos_dot_bidirectional__rnn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/text_generator.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bprotos/text_generator.proto\x12\x06protos\x1a\x14protos/convnet.proto\x1a\x18protos/hyperparams.proto\x1a\x11protos/loss.proto\x1a\x1eprotos/bidirectional_rnn.proto\"\xa8\x01\n\rTextGenerator\x12\x33\n\x11\x62idirectional_rnn\x18\x01 \x03(\x0b\x32\x18.protos.BidirectionalRnn\x12 \n\x07\x63onvnet\x18\x02 \x01(\x0b\x32\x0f.protos.Convnet\x12\x1a\n\x04loss\x18\x03 \x01(\x0b\x32\x0c.protos.Loss\x12$\n\x15summarize_activations\x18\x04 \x01(\x08:\x05\x66\x61lse'
  ,
  dependencies=[protos_dot_convnet__pb2.DESCRIPTOR,protos_dot_hyperparams__pb2.DESCRIPTOR,protos_dot_loss__pb2.DESCRIPTOR,protos_dot_bidirectional__rnn__pb2.DESCRIPTOR,])




_TEXTGENERATOR = _descriptor.Descriptor(
  name='TextGenerator',
  full_name='protos.TextGenerator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bidirectional_rnn', full_name='protos.TextGenerator.bidirectional_rnn', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='convnet', full_name='protos.TextGenerator.convnet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loss', full_name='protos.TextGenerator.loss', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summarize_activations', full_name='protos.TextGenerator.summarize_activations', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=307,
)

_TEXTGENERATOR.fields_by_name['bidirectional_rnn'].message_type = protos_dot_bidirectional__rnn__pb2._BIDIRECTIONALRNN
_TEXTGENERATOR.fields_by_name['convnet'].message_type = protos_dot_convnet__pb2._CONVNET
_TEXTGENERATOR.fields_by_name['loss'].message_type = protos_dot_loss__pb2._LOSS
DESCRIPTOR.message_types_by_name['TextGenerator'] = _TEXTGENERATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextGenerator = _reflection.GeneratedProtocolMessageType('TextGenerator', (_message.Message,), {
  'DESCRIPTOR' : _TEXTGENERATOR,
  '__module__' : 'protos.text_generator_pb2'
  # @@protoc_insertion_point(class_scope:protos.TextGenerator)
  })
_sym_db.RegisterMessage(TextGenerator)


# @@protoc_insertion_point(module_scope)
